### ISSUE TITLE
Request for change in YAML format

### ISSUE THREAD

**Issue by DevPranjal** [dsgiitr/ML-InterviewQs#17]
Currently, the questions are stored as:
```yaml
questions:
   title: ...
   .
   .
  
   title: ...
   .
   .
```
This leads to a complicated parsing with template languages (such as [Liquid](https://jekyllrb.com/docs/liquid/) used in Jekyll) due to no separation of levels between questions

A better format according to me would be:
```yaml
- title: ...
  .
  .

- title: ...
  .
  .
```

This would have a simple parsing template as follows:
```markdown
{% for question in site.data.ml %}

{{ question.text }}

{% for opt in question.opt %}

- {{ opt }}

{% endfor %}

{% endfor %}
```

**Comment by Garg-Doppler** [comment]
In the proposed format, would other keys be nested inside the `title` key?

**Comment by DevPranjal** [comment]
No. Something like this:
```yaml
- title: ...
  type: ...
  text: ...

- title: ...
  type: ...
  text: ...
```

**Comment by Garg-Doppler** [comment]
Well, it makes sense to do this if the parsing template simplifies. Also, it makes logical sense to do this, since each question is a list item, and each list item must begin with a `-`.
