### ISSUE TITLE
Request for adding a new tag for probability

### ISSUE THREAD

**Issue by divo12** [dsgiitr/ML-InterviewQs#18]
Currently we have a tag for `statistics` but there are certain questions which are completely probabilistic so we require a tag for `probability`

**Comment by Garg-Doppler** [comment]
I've assigned the issue to you. Kindly make a commit in `tags.md` to resolve this issue. Thanks.

**Comment by divo12** [comment]
I have pushed the updated tags.md. You can merge #16 and close the issue :-)
